---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backend-secret
  namespace: todolist
spec:
  encryptedData:
    DB_PASSWORD: AgAkj7jCkbsSxNjlavSXT7jVWUDpyhd3V6lZWMKamcqRFzheWCsIIUsoW3iIZRJRsgMBKv/4P1ZNB23ctM1ZIHnh/3ihA0Se0KN1Rfu1fgZy6nDYTqO2imGJBXnpWjvbcd3k0/UmQ+sgb9ZqvCIqs5NXLrX1iYzFAl/0jx7XweXIGu7OtpuTS9ZeVcDMx85nZd/6NMRVXzpXLHrbuGcCTYXhS65vfGpFK4z+avCHTgk3KkGCFbEfJTwH+iTw86sUcrqqP0GRHkUaJez33dSAeOmxnxsctu1ifzhKcg3K0IOCkEWgKA/Pt7O/2+CllIfy0oRF4vxV6wj+gRnckpZM6o7oHmtba3n+zyqfTp46YxSLZmuXJzx4Q8QKvYQjX+T3Zcde/xkLjr/lFpIDsPhvc3XBDwe3u57T5omy/C0X//D0GMYJQ6gbIkxng/o4462aIcpWMZxz3vFNAvHErkoh9aHLma40wzyjKGgL9ZPKEjEh2dW1KVZ5QhSHcupf8nS7OkM6A9h28Fvhk0S24mDamZpeLqo1v51jaPE8d6K8IFk7kMfWV5mfl3C46psHr0rExt71mpbwrWKqualtkd1PkfB2lVFj1jSL5/k3g7Nnxkqs1Yv5hvu+6AFrWpPaECc5o12tgFuTrnK8dfnJVU7YKFA6InQPr58INlFTzIocoO5yMEoUNVGm1w+oiHIklHsmqPV3ZSXBl+gCkAmC0Lg=
    DB_USER: AgCvCIjwsELySojRMZ3SQ9Caf5RYzJm9z14TDMrbxxE8NSrIJMEEi+zOobQUcNXecvEBY/KBCrCwMML/tNOkSHmC/65+a17r9aDNXLsuV7I2b3kwjQSysxd8m6dJ8RAGIXco6uWcm6Ejjpo6crf+gPe99CzW0AhxoPNSFkBAhWFUpk8ue7OQUGI3spCkcSi+67KNnZRe3TmJ1QAfsgThLe4KQo0rUcpFAdawJjUzQx/E/Nj17Colfd8uomBuuJSJ2+aHv7+vE7NuCiJuHRWV4JR5RJ2NGpChSx/jsafl28aqZ9n1g0zNFx8legbhBLa1lr4fPMGEHe3CYKjQH+Zw+fnNi8vewg/GuoYCWO3gYJyjSwm66uaK1J66TK8E9R4LeF5zAk7kbF1ERU8hsnwKCSUVlIhEq8q98QvCpoDJFd6PScU+a0qUkSaNCuTOoIBI/WB+d45/kboArh7QO21TSb780gpsLwZ0w6xNwZjHbQRV+E9/kk2PplgbLLkz+d3RldvEAuybMiUUUUHaEzkWOg9M+nxLCV49SES9vxMPxXekbriSEPNCO9PNo3RuSrCtlhWgapMoCWjNBXf2vx3l5HOEz0ghRfxY7J2yv0/t0Y1n22rlK/yFDUCFhGBApQE8HyzipCEZIkhWlmAeqaJerUcxkHaf9KQ9q5A4DdDrzkd1BUaNzJZOw1mIw9j+sQMaq+F25kXwlRl72PVk8aw=
  template:
    metadata:
      creationTimestamp: null
      name: backend-secret
      namespace: todolist
    type: Opaque
