apiVersion: v1
kind: ServiceAccount
metadata:
  name: todolist-sa
  namespace: todolist
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: todolist-pod-creator
  namespace: todolist
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: todolist-pod-creator-binding
  namespace: todolist
subjects:
  - kind: ServiceAccount
    name: todolist-sa
    namespace: todolist
roleRef:
  kind: Role
  name: todolist-pod-creator
  apiGroup: rbac.authorization.k8s.io
